%% gen_examples.m  —  build test_data/examples/<analysis>/ : input CSV(s) + report
% One folder per analysis, each holding its synthetic_gui import CSV(s) and a
% freshly generated combined HTML report (.mat/.xlsx/topo PNGs too). Mirrors the
% GUI analyses; pairs with the Notion "SnPMAnalysisGUI-v2" docs.
%
% Run headless from repo root:
%   matlab -batch "run('scripts/gen_examples.m')"

ROOT = fileparts(fileparts(mfilename('fullpath')));   % scripts/ -> repo root
if isempty(ROOT), ROOT = pwd; end
SRC  = fullfile(ROOT,'test_data','synthetic_gui');
DST  = fullfile(ROOT,'test_data','examples');
addpath(genpath(ROOT));

channels = 'egi'; datatype = 'absolute'; nperm = 500;
if ~exist(DST,'dir'), mkdir(DST); end

% ---- GLM presets: single file -> core_snpm_glm ----
% columns: folder | comparison | csv | meta_cols | roles-struct
% (folder and comparison differ only for mixed2way_2x3, a 2nd mixed2way shape)
glm = {
  'anova1'        'anova1'    'glm_anova1.csv'    {'Subject','group'}              struct('group_col','group');
  'ancova'        'ancova'    'glm_ancova.csv'    {'Subject','group','age','sex'}  struct('group_col','group','covariate_cols',{{'age','sex'}});
  'ancova3'       'ancova'    'glm_ancova3.csv'   {'Subject','group','age','sex'}  struct('group_col','group','covariate_cols',{{'age','sex'}});
  'regression'    'regression' 'glm_regression.csv' {'Subject','cognition','age'}  struct('predictor_col','cognition','covariate_cols',{{'age'}});
  'rmanova'       'rmanova'   'glm_rmanova.csv'   {'Subject','condition'}          struct('subject_col','Subject','condition_col','condition');
  'mixed2way'     'mixed2way' 'glm_mixed2way.csv' {'Subject','group','condition'}  struct('group_col','group','subject_col','Subject','condition_col','condition');
  'mixed2way_2x3' 'mixed2way' 'glm_mixed2way_2x3.csv' {'Subject','group','condition'} struct('group_col','group','subject_col','Subject','condition_col','condition');
};
for i = 1:size(glm,1)
    key = glm{i,1}; comp = glm{i,2}; csv = glm{i,3}; meta = glm{i,4}; roles = glm{i,5};
    outdir = fullfile(DST,key); if ~exist(outdir,'dir'), mkdir(outdir); end
    copyfile(fullfile(SRC,csv), fullfile(outdir,csv));
    p = struct('comparison',comp,'data_file',fullfile(outdir,csv),'data_sheet','CSV File', ...
        'output_path',outdir,'channels',channels,'datatype',datatype,'permutations',nperm, ...
        'snpm_path',ROOT,'meta_cols',{meta});
    fn = fieldnames(roles); for k=1:numel(fn), p.(fn{k}) = roles.(fn{k}); end
    core_snpm_analysis(p);
    fprintf('Done: %s\n', key);
end

% ---- LMM: long-format single file -> core_snpm_lmm ----
outdir = fullfile(DST,'lmm'); if ~exist(outdir,'dir'), mkdir(outdir); end
copyfile(fullfile(SRC,'lmm_long.csv'), fullfile(outdir,'lmm_long.csv'));
p = struct('comparison','mixedmodel','data_file',fullfile(outdir,'lmm_long.csv'),'data_sheet','CSV File', ...
    'output_path',outdir,'channels',channels,'datatype',datatype,'permutations',nperm,'tail','both', ...
    'snpm_path',ROOT,'lmm_dv','sleepDepth','lmm_fixed','POWER','lmm_random','(1|Subject)', ...
    'lmm_effect','POWER','lmm_effect_type','continuous','lmm_meta_cols',{{'Subject','group','time','sleepDepth'}});
core_snpm_analysis(p);
fprintf('Done: lmm\n');

% ---- One-sample: single condition tested vs 0 (no Data 2) ----
outdir = fullfile(DST,'onesampleT'); if ~exist(outdir,'dir'), mkdir(outdir); end
copyfile(fullfile(SRC,'onesample_change.csv'), fullfile(outdir,'onesample_change.csv'));
p = struct('comparison','onesampleT','data1_file',fullfile(outdir,'onesample_change.csv'), ...
    'data1_sheet','CSV File','data2_file','','output_path',outdir,'channels',channels, ...
    'datatype',datatype,'permutations',nperm,'tail','both','use_covariates',false,'snpm_path',ROOT);
core_snpm_analysis(p);
fprintf('Done: onesampleT (single condition vs 0)\n');

% ---- Legacy two-file tests -> core_snpm_analysis (compstring) ----
leg = {
  'pairedT'     'paired_condA.csv'    'paired_condB.csv'    'pairedT';
  'unpairedT'   'unpaired_groupA.csv' 'unpaired_groupB.csv' 'unpairedT';
  'correlation' 'corr_eeg.csv'        'corr_behavior.csv'   'correlationP';
};
for i = 1:size(leg,1)
    key = leg{i,1}; a = leg{i,2}; b = leg{i,3}; comp = leg{i,4};
    outdir = fullfile(DST,key); if ~exist(outdir,'dir'), mkdir(outdir); end
    copyfile(fullfile(SRC,a), fullfile(outdir,a));
    copyfile(fullfile(SRC,b), fullfile(outdir,b));
    p = struct('comparison',comp, ...
        'data1_file',fullfile(outdir,a),'data1_sheet','CSV File', ...
        'data2_file',fullfile(outdir,b),'data2_sheet','CSV File', ...
        'output_path',outdir,'channels',channels,'datatype',datatype, ...
        'permutations',nperm,'tail','both','use_covariates',false,'snpm_path',ROOT);
    core_snpm_analysis(p);
    fprintf('Done: %s (%s)\n', key, comp);
end

% ---- Circular (phase/angle) tier -> core_snpm_circ ----
% Angles are radians on [0,2pi) with zero at the up-state peak, so units='rad'
% and convention='literature_uppeak0'. The two group analyses REQUIRE the event
% count files; the circular-linear analysis does not (it pairs by subject).
circ = {
  'circular_phase_hotelling' 'circ_phase_group'    'circ_phase_groupA.csv' 'circ_phase_groupB.csv' 'circ_phase_countsA.csv' 'circ_phase_countsB.csv';
  'circular_phase_watsonu2'  'circ_phase_group_u2' 'circ_phase_groupA.csv' 'circ_phase_groupB.csv' 'circ_phase_countsA.csv' 'circ_phase_countsB.csv';
  'circular_concentration'   'circ_phase_group'    'circ_conc_groupA.csv'  'circ_conc_groupB.csv'  'circ_conc_countsA.csv'  'circ_conc_countsB.csv';
};
for i = 1:size(circ,1)
    key = circ{i,1}; comp = circ{i,2};
    outdir = fullfile(DST,key); if ~exist(outdir,'dir'), mkdir(outdir); end
    for k = 3:6, copyfile(fullfile(SRC,circ{i,k}), fullfile(outdir,circ{i,k})); end
    p = struct('comparison',comp, ...
        'data1_file',fullfile(outdir,circ{i,3}),'data1_sheet','CSV File', ...
        'data2_file',fullfile(outdir,circ{i,4}),'data2_sheet','CSV File', ...
        'count1_file',fullfile(outdir,circ{i,5}),'count2_file',fullfile(outdir,circ{i,6}), ...
        'output_path',outdir,'channels',channels,'datatype','absolute', ...
        'permutations',nperm,'tail','both','circ_units','rad', ...
        'circ_convention','literature_uppeak0','snpm_path',ROOT);
    core_snpm_analysis(p);
    fprintf('Done: %s (%s)\n', key, comp);
end

outdir = fullfile(DST,'circular_anglinear'); if ~exist(outdir,'dir'), mkdir(outdir); end
copyfile(fullfile(SRC,'circ_anglinear_angles.csv'),  fullfile(outdir,'circ_anglinear_angles.csv'));
copyfile(fullfile(SRC,'circ_anglinear_measure.csv'), fullfile(outdir,'circ_anglinear_measure.csv'));
p = struct('comparison','circ_corrAngLinear', ...
    'data1_file',fullfile(outdir,'circ_anglinear_angles.csv'),'data1_sheet','CSV File', ...
    'data2_file',fullfile(outdir,'circ_anglinear_measure.csv'),'data2_sheet','CSV File', ...
    'measure_col','measure','output_path',outdir,'channels',channels,'datatype','absolute', ...
    'permutations',nperm,'tail','both','circ_units','rad', ...
    'circ_convention','literature_uppeak0','snpm_path',ROOT);
core_snpm_analysis(p);
fprintf('Done: circular_anglinear (circ_corrAngLinear)\n');

% ---- examples/README.md : folder -> analysis -> GUI settings ----
fid = fopen(fullfile(DST,'README.md'),'w');
fprintf(fid, ['# Example analyses \x2014 one folder per analysis\n\n', ...
 'Each folder holds the import CSV(s) and the report SnPM produces from them.\n', ...
 'All use the **EGI 256 (HydroCel)** system (E1..E256), Data Type **absolute**, with a\n', ...
 'planted 17-channel cluster near E129. Generated by `scripts/gen_examples.m` (500 perms).\n\n', ...
 '| folder | analysis | input CSV(s) | roles |\n|---|---|---|---|\n', ...
 '| `anova1` | One-way ANOVA (3+ groups) | glm_anova1.csv | Group=group |\n', ...
 '| `ancova` | One-way ANCOVA (2 groups \x2192 t) | glm_ancova.csv | Group=group, Covariates=age,sex |\n', ...
 '| `ancova3` | One-way ANCOVA (3 groups \x2192 F + post-hoc) | glm_ancova3.csv | Group=group, Covariates=age,sex |\n', ...
 '| `regression` | Multiple linear regression | glm_regression.csv | Predictor=cognition, Covariates=age |\n', ...
 '| `rmanova` | Repeated-measures ANOVA | glm_rmanova.csv | Subject=Subject, Condition=condition |\n', ...
 '| `mixed2way` | Two-way mixed ANOVA (2\xD72: pre/post) | glm_mixed2way.csv | Group=group, Subject=Subject, Condition=condition |\n', ...
 '| `mixed2way_2x3` | Two-way mixed ANOVA (2\xD73: pre/mid/post) | glm_mixed2way_2x3.csv | Group=group, Subject=Subject, Condition=condition |\n', ...
 '| `pairedT` | Paired t-test | paired_condA.csv + paired_condB.csv | \x2014 |\n', ...
 '| `onesampleT` | One-sample t-test (single condition vs 0) | onesample_change.csv | \x2014 |\n', ...
 '| `unpairedT` | Two independent-samples t-test | unpaired_groupA.csv + unpaired_groupB.csv | \x2014 |\n', ...
 '| `correlation` | Pearson correlation | corr_eeg.csv + corr_behavior.csv | \x2014 |\n', ...
 '| `lmm` | Linear Mixed Model | lmm_long.csv | DV=sleepDepth, fixed=POWER |\n', ...
 '| `circular_phase_hotelling` | Phase, 2 groups (Hotelling T\xB2) | circ_phase_group{A,B}.csv + circ_phase_counts{A,B}.csv | units=rad, convention=literature_uppeak0 |\n', ...
 '| `circular_phase_watsonu2` | Phase, 2 groups (Watson U\xB2) | same four files | units=rad, convention=literature_uppeak0 |\n', ...
 '| `circular_concentration` | Concentration difference at the same mean (Hotelling) | circ_conc_group{A,B}.csv + circ_conc_counts{A,B}.csv | units=rad, convention=literature_uppeak0 |\n', ...
 '| `circular_anglinear` | Circular-linear correlation | circ_anglinear_angles.csv + circ_anglinear_measure.csv | measure_col=measure |\n\n', ...
 'The circular angle files are **radians on [0,2\x3C0)** with zero at the slow-oscillation\n', ...
 'up-state peak. The two group analyses **require** the event-count files. The\n', ...
 '`circular_concentration` example plants a Hahn-2020-magnitude concentration difference\n', ...
 '(\x3BA 14.2 vs 3.94) at 20+20 subjects, where detection is only ~22%% likely \x2014 a null\n', ...
 'report there is the expected outcome, not a defect.\n']);
fclose(fid);
fprintf('\nAll examples written to %s\n', DST);
